"""Swagger 中使用的通俗中文说明。

这里的文字只解释公开 HTTP 接口已经存在的字段和行为，不定义新的业务概念。
"""

from __future__ import annotations

SUMMARY_TRANSLATIONS = {
    "Acquire Exclusive": "取得设备的手动使用权",
    "Action schema": "查询设备动作的参数格式",
    "All available actions": "查询所有可用的设备动作",
    "Api Readiness": "查询服务是否已准备好",
    "Append Material State": "新增一条物料状态记录",
    "Apply Authoring": "应用工作流源码草稿",
    "Assembly": "查询物料的装配关系",
    "Authoring device catalog": "查询工作流编辑器可用的设备",
    "Backend-compatible device list": "查询设备列表",
    "Batch Delete Workflow Graph": "批量删除工作流节点和连线",
    "Begin Scheduler Drain": "暂停派发新的设备任务",
    "Browse files and directories": "浏览文件和文件夹",
    "Cancel": "取消入库预留",
    "Command Debug Workflow Task": "控制调试中的工作流任务",
    "Command Workflow Task": "控制工作流任务",
    "Commit Feedback": "提交设备任务的过程反馈",
    "Commit Joint States": "提交设备关节状态",
    "Commit Kinematic Attachments": "提交设备的装配关系",
    "Commit Outcome": "提交设备任务的最终结果",
    "Commit Properties": "提交设备属性",
    "Compile Authoring": "检查并编译工作流编辑内容",
    "Create Current Substance": "新增物料中的当前成分",
    "Create Debug Workflow Task": "创建调试工作流任务",
    "Create Device Action Run": "创建一次设备动作任务",
    "Create Material": "新增物料",
    "Create Reagent": "新增试剂库存",
    "Create Reagent Infos Batch": "批量新增试剂身份",
    "Create Reagent Info": "新增试剂信息",
    "Create Reagents Batch": "批量新增试剂库存",
    "Create Sample": "新增样品",
    "Create Workflow": "创建工作流",
    "Create Workflow Edge": "新增工作流连线",
    "Create Workflow Node": "新增工作流节点",
    "Create Workflow Task": "创建工作流任务",
    "Create job": "创建设备任务",
    "Decide Manual Confirmation": "提交人工确认结果",
    "Delete Current Substance": "删除物料中的当前成分",
    "Delete Material": "删除物料",
    "Delete Reagent": "删除试剂库存",
    "Delete Reagent Info": "删除试剂信息",
    "Delete Resource Template": "删除资源模板",
    "Delete Sample": "删除样品",
    "Delete Workflow": "删除工作流",
    "Delete Workflow Edge": "删除工作流连线",
    "Delete Workflow Node": "删除工作流节点",
    "Demo": "写入实验室布局示例数据",
    "Device State All": "查询所有设备的当前状态",
    "Device State History": "查询一个设备属性的历史记录",
    "Device State History All": "查询设备状态的历史记录",
    "Device State One": "查询一个设备的当前状态",
    "Device State Report": "上报设备状态",
    "Device actions list": "查询一个设备的可用动作",
    "Duplicate Workflow": "复制工作流",
    "Duplicate Workflow Node": "复制工作流节点",
    "Events": "接收工作流变化通知",
    "Fetch Job": "查询待执行的设备任务",
    "Finish Job": "提交设备任务完成结果",
    "Force Release Workflow Task Execution Lock": "人工释放工作流任务执行锁",
    "Generate Authoring Python": "把工作流编辑内容生成 Python 源码",
    "Get": "查询入库预留",
    "Get Authoring": "查询工作流源码和草稿",
    "Get Current Substance": "查询物料中的当前成分",
    "Get Current Substance By Material": "按物料查询当前成分",
    "Get Debug Workflow Task": "查询调试工作流任务",
    "Get Execution Wait Graph": "查询任务等待关系",
    "Get Graph": "查询工作流完整图",
    "Get Instance": "查询一个库存实例",
    "Get Lot": "查询一个库存批次",
    "Get Manual Confirmation": "查询一条人工确认",
    "Get Material": "查询一个物料",
    "Get Material Graph": "查询物料之间的关系图",
    "Get Material State": "查询一条物料状态记录",
    "Get Node Template": "查询一个工作流节点模板",
    "Get Package Mounts": "查询当前工作区加载的领域包",
    "Get Reagent": "查询一条试剂库存",
    "Get Reagent History": "查询一条试剂变更记录",
    "Get Reagent Info": "查询一条试剂信息",
    "Get Reagent Info Structure": "查询试剂的三维结构文件",
    "Get Reservation": "查询一条库存预留",
    "Get Reservations": "查询工作流使用的库存预留",
    "Get Resource Template": "查询一个资源模板",
    "Get Sample": "查询一个样品",
    "Get Site": "查询一个库位",
    "Get Substance History": "查询一条成分变更记录",
    "Get Template": "查询一个库存模板",
    "Get Workflow": "查询一个工作流",
    "Get Workflow Intervention": "查询一条待处理事项",
    "Get Workflow Node": "查询一个工作流节点",
    "Get Workflow Node Job": "查询一个节点任务",
    "Get Workflow Run Preflight": "检查工作流是否可以运行",
    "Get Workflow Task": "查询一个工作流任务",
    "Get Workflow Task Step State": "查询工作流任务单步状态",
    "Health": "查询库存服务是否正常",
    "History Jobs": "查询设备任务历史",
    "History Workflow Detail": "查询一次工作流运行详情",
    "History Workflows": "查询工作流运行历史",
    "Home Page": "打开接口首页",
    "Hostlink Peers": "查询主从设备连接状态",
    "Import Legacy Workflow": "导入旧格式工作流",
    "Import Python Workflow": "导入 Python 工作流文件",
    "Import Reagent Infos": "从文件导入试剂身份",
    "Import Reagents": "从文件导入试剂库存",
    "Insert Composite Workflow": "在工作流中插入子工作流",
    "Job status": "查询设备任务状态",
    "Latest Material State": "查询物料的最新状态",
    "Layout": "查询实验室布局",
    "Ledger": "查询库存变更流水",
    "List Contents": "查询库存内容列表",
    "List Current Substances": "查询物料当前成分列表",
    "List Error Decisions": "查询等待人工处理的设备错误",
    "List Instances": "查询库存实例列表",
    "List Job Inventory Consumptions": "查询节点任务的库存消耗",
    "List Lots": "查询库存批次列表",
    "List Material Shapes": "查询物料外形列表",
    "List Material States": "查询物料状态记录",
    "List Materials": "查询物料列表",
    "List Node Templates": "查询工作流节点模板",
    "List Reagent History": "查询物料的试剂变更记录",
    "List Reagent Infos": "查询试剂信息列表",
    "List Reagent Inventory Consumptions": "查询试剂的工作流消耗记录",
    "List Reagents": "查询试剂库存列表",
    "List Relations": "查询库存关系列表",
    "List Reservations": "查询库存预留列表",
    "List Resource Templates": "查询资源模板列表",
    "List Samples": "查询样品列表",
    "List Sites": "查询物料可用的库位",
    "List Substance History": "查询物料的成分变更记录",
    "List Task Inventory Consumptions": "查询工作流任务的库存消耗",
    "List Task Manual Confirmations": "查询任务中的人工确认",
    "List Templates": "查询库存模板列表",
    "List Workflow Change Log": "查询工作流修改记录",
    "List Workflow Interventions": "查询等待处理的工作流事项",
    "List Workflow Node Job Feedback": "查询节点任务的过程反馈",
    "List Workflow Node Jobs": "查询工作流任务中的节点任务",
    "List Workflow Nodes": "查询工作流节点列表",
    "List Workflow Task Execution Locks": "查询工作流任务的执行锁",
    "List Workflow Task Presentations": "查询工作流任务展示列表",
    "List Workflow Task Runtime Events": "查询工作流任务运行记录",
    "List Workflow Tasks": "查询工作流任务列表",
    "List Workflows": "查询工作流列表",
    "Lookup Compound": "按化学品登记号（CAS 号）查询化合物信息",
    "Manual Reschedule": "立即重新计算任务安排",
    "Mark In Transit": "把入库预留标记为运输中",
    "Monitor Events": "接收调度状态变化",
    "Monitor Snapshot": "查询调度监控快照",
    "Online devices list": "查询在线设备",
    "Open Local Folder": "在本机打开文件夹",
    "Outbox Backlog": "查询尚未确认的库存事件数量",
    "Outbox Events": "查询尚未确认的库存事件",
    "Patch Workflow Node": "修改工作流节点",
    "Post Command": "提交库存操作命令",
    "Post Placement": "新增或修改实验室摆放位置",
    "Post Workflow Run Preflight": "按给定参数检查工作流是否可以运行",
    "Post Zone": "新增或修改实验室区域",
    "Preflight Debug Workflow Task": "检查调试任务是否可以创建",
    "Process health": "查询进程是否存活",
    "Processed Commands": "查询已经处理的库存命令",
    "Profile": "查询实验室基本信息",
    "Put Profile": "修改实验室基本信息",
    "Query Material": "按条件查询物料",
    "Read Exclusive": "查询设备的手动使用权",
    "Read Material Model": "读取物料三维模型文件",
    "Readiness": "查询设备任务通信是否已准备好",
    "Receive": "确认入库物料已收到",
    "Register Session": "登记设备运行进程",
    "Registry Editor": "打开注册表编辑页面",
    "Release Exclusive": "释放设备的手动使用权",
    "Remove Placement": "删除实验室摆放位置",
    "Remove Zone": "删除实验室区域",
    "Reserve": "创建入库预留",
    "Resolve Error Decision": "提交设备错误处理结果",
    "Resolve Registered Unknown": "确认设备未知任务的处理结果",
    "Resolve Uncertain Workflow Node Job": "确认状态不确定的节点任务结果",
    "Resolve Unknown": "确认未知设备任务的处理结果",
    "Resource list": "查询资源列表",
    "Resume Scheduler From Drain": "恢复派发设备任务",
    "Save Draft": "保存工作流源码草稿",
    "Save Graph": "保存工作流完整图",
    "Scheduler Drain Status": "查询是否已暂停派发设备任务",
    "Select Workflow Intervention": "提交工作流待处理事项的选择",
    "Settle Failed Material Transfer": "登记失败转运后的实际物料位置",
    "Snapshot": "查询库存完整快照",
    "Stream Device Telemetry": "接收设备状态变化",
    "Submit Station Workflow": "接收并创建工站工作流任务",
    "Sync Cursors": "查询库存同步进度",
    "Sync Resource Templates": "同步资源模板",
    "System Status": "打开系统状态页面",
    "Timeline": "查询设备任务时间线",
    "Update Current Substance": "修改物料中的当前成分",
    "Update Device Status": "更新设备在线状态",
    "Update Material": "修改物料",
    "Update Reagent": "修改试剂库存",
    "Update Reagent Info": "修改试剂信息",
    "Update Resource Template": "修改资源模板",
    "Update Sample": "修改样品",
    "Update Workflow": "修改工作流",
    "Validate Authoring": "检查工作流编辑内容",
    "Warehouse": "查询按类别汇总的库存",
}


OPERATION_DESCRIPTIONS = {
    ("DELETE", "/api/v1/workflows/{workflow_uuid}"): "删除指定工作流及其保存的图。删除前会检查该工作流是否允许删除。",
    ("PUT", "/api/v1/workflows/{workflow_uuid}/graph"): "用请求体中的节点和连线保存指定工作流的完整图。修改版本号不一致时不会覆盖已有内容。",
    ("PATCH", "/api/v1/workflow-nodes/{node_uuid}"): "只修改请求体中明确提供的节点字段，未提供的字段保持不变。",
    ("DELETE", "/api/v1/workflow-nodes/{node_uuid}"): "删除指定节点，并按照现有校验规则处理与它相连的连线。",
    ("POST", "/api/v1/workflow-nodes/{node_uuid}/duplicate"): "复制指定节点；请求体可以提供复制后的新名称。",
    ("DELETE", "/api/v1/workflow-edges/{edge_uuid}"): "删除指定工作流连线。",
    ("POST", "/api/v1/reagent-infos/batch"): "批量创建试剂身份。请求体为 items 数组，默认 atomic=true，任一行校验或写入失败时整批回滚；设置 atomic=false 可保留有效行并在 errors 中返回失败行。",
    ("POST", "/api/v1/reagent-infos/import"): "从 multipart/form-data 的 file 字段导入试剂身份，支持 UTF-8 编码的 JSON、CSV、TSV 文件和 XLSX 文件；默认原子导入，可通过 atomic=false 逐行导入。",
    ("POST", "/api/v1/reagents/batch"): "批量创建容器级试剂。请求体为 items 数组，默认 atomic=true，任一行校验或写入失败时整批回滚；设置 atomic=false 可保留有效行并在 errors 中返回失败行。",
    ("POST", "/api/v1/reagents/import"): "从 multipart/form-data 的 file 字段导入容器级试剂，支持 UTF-8 编码的 JSON、CSV、TSV 文件和 XLSX 文件；默认原子导入，可通过 atomic=false 逐行导入。",
    ("GET", "/api/v1/debug/workflow-tasks/{task_uuid}"): "查询一条调试工作流任务的当前状态和调试信息。",
    ("POST", "/api/v1/debug/workflow-tasks/{task_uuid}/commands"): "向调试工作流任务提交继续、暂停或其他已支持的控制命令。重复请求使用同一个防重复编号时，不会重复执行。",
    ("GET", "/api/v1/workflow-tasks/{task_uuid}"): "查询一条工作流任务的当前状态和运行信息。",
    ("GET", "/api/v1/workflow-tasks/{task_uuid}/jobs"): "查询指定工作流任务拆分出的全部节点任务。",
    ("GET", "/api/v1/workflow-tasks/{task_uuid}/execution-locks"): "查询指定工作流任务当前活动的设备、物料和库位执行锁，并返回人工释放资格。",
    ("POST", "/api/v1/workflow-tasks/{task_uuid}/execution-locks/{lease_uuid}/force-release"): "在物理安全确认和 Claim/Fence 并发校验通过后，释放指定节点作业持有的全部执行锁并记录审计。",
    ("GET", "/api/v1/workflow-tasks/{task_uuid}/manual-confirmations"): "查询指定工作流任务中需要或已经完成人工确认的记录。",
    ("GET", "/api/v1/workflow-node-jobs/{job_uuid}"): "查询一条节点任务的当前状态、执行信息和结果。",
    ("POST", "/api/v1/workflow-node-jobs/{job_uuid}/resolve-uncertain"): "人工确认状态不确定的节点任务最终应按成功还是失败处理。",
    ("GET", "/api/v1/workflow-manual-confirmations/{confirmation_uuid}"): "查询一条人工确认的内容和当前处理状态。",
    ("POST", "/api/v1/workflow-manual-confirmations/{confirmation_uuid}/decision"): "提交一条人工确认的通过、拒绝或其他已支持结果。",
    ("GET", "/api/v1/workflow-interventions/{intervention_uuid}"): "查询一条等待人工处理的工作流事项及可选处理方式。",
    ("POST", "/api/v1/workflow-interventions/{intervention_uuid}/decisions"): "选择并提交一条工作流待处理事项的处理方式。",
    ("GET", "/api/v1/workflows/{workflow_uuid}/authoring"): "查询指定工作流当前保存的 Python 源码、草稿和修改版本。",
    ("PUT", "/api/v1/workflows/{workflow_uuid}/authoring/draft"): "保存指定工作流的 Python 源码草稿，不会直接替换正在使用的工作流图。",
    ("POST", "/api/v1/jobs/{job_id}/finish"): "由设备执行端提交任务是否成功以及返回内容；提交后会触发后续任务安排。",
    ("POST", "/api/v1/reschedule"): "立即重新计算可执行任务，主要用于人工触发检查。",
    ("GET", "/api/v1/device-state/{device_id}"): "查询指定设备最近一次保存的全部属性值。",
    ("POST", "/api/v1/error-decisions/{decision_id}"): "提交指定设备错误的处理方式，例如重试、跳过或终止。",
}


PARAMETER_MEANINGS = {
    "Idempotency-Key": "本次处理的唯一键；相同键重复提交时不会重复处理。",
    "Last-Event-ID": "上一次已经收到的事件编号；服务从它之后继续发送。",
    "X-Command-UUID": "本次设备命令的唯一编号。",
    "X-Job-Token": "设备任务访问凭证。",
    "X-Workflow-Filename": "导入文件的文件名，只写文件名，不要包含文件夹路径。",
    "action_name": "设备动作名称。",
    "after_id": "只返回编号大于该值的记录。",
    "after_sequence": "只返回顺序号大于该值的记录。",
    "asset_path": "模型文件在领域包中的相对路径。",
    "authorization": "工站调用使用的访问凭证。",
    "backlog": "建立连接时先返回的最近事件条数。",
    "barcode": "物料条码；不填写时不按条码筛选。",
    "before_time": "只返回该时间之前的记录。",
    "before_uuid": "同一时间下，从该记录编号之前继续查询。",
    "cas": "化合物的登记号（CAS 号）。",
    "category_uuid": "实验操作类别的唯一编号（UUID）。",
    "channels": "要接收的事件类型，多个值用英文逗号分隔；不填写时接收全部。",
    "cleanup_status": "任务清理状态；不填写时不过滤。",
    "code": "用于精确筛选的编码。",
    "confirmation_uuid": "人工确认记录的唯一编号（UUID）。",
    "decision_id": "待处理设备错误的编号。",
    "device_id": "设备编号。",
    "edge_uuid": "库存实例的唯一编号（UUID）。",
    "execution_kind": "任务来源类型；不填写时不过滤。",
    "history_uuid": "历史记录的唯一编号（UUID）。",
    "id": "设备任务编号。",
    "intervention_uuid": "工作流待处理事项的唯一编号（UUID）。",
    "job_id": "设备任务编号。",
    "job_uuid": "节点任务的唯一编号（UUID）。",
    "keyword": "名称关键字；不填写时不过滤。",
    "limit": "本次最多返回的记录数。",
    "local_device_id": "设备在当前运行进程中的编号。",
    "lot_id": "库存批次编号。",
    "material_uuid": "物料的唯一编号（UUID）。",
    "name": "名称关键字；不填写时不过滤。",
    "node_type": "工作流节点类型；不填写时不过滤。",
    "node_uuid": "工作流节点的唯一编号（UUID）。",
    "operation_category_uuid": "实验操作类别的唯一编号（UUID）；不填写时不过滤。",
    "page": "页码，从 1 开始。",
    "page_size": "每页返回的数量。",
    "path": "要浏览或打开的本机文件夹路径。",
    "physical_state": "试剂的物理状态；不填写时不过滤。",
    "property": "要查询历史记录的设备属性名称。",
    "reagent_info_uuid": "试剂信息的唯一编号（UUID）。",
    "reagent_uuid": "试剂库存的唯一编号（UUID）。",
    "reservation_id": "库存预留编号。",
    "reservation_uuid": "入库预留的唯一编号（UUID）。",
    "resource_template_uuid": "资源模板的唯一编号（UUID）；不填写时不过滤。",
    "resource_type": "资源类型；不填写时不过滤。",
    "run_mode": "运行方式；不填写时按普通方式检查。",
    "sample_uuid": "样品的唯一编号（UUID）。",
    "session_uuid": "设备运行进程会话的唯一编号（UUID）。",
    "since": "只返回该时间之后的记录，使用 Unix 时间戳秒数。",
    "since_ms": "只返回该时间之后的记录，使用 Unix 时间戳毫秒数。",
    "site_uuid": "库位的唯一编号（UUID）。",
    "state": "运行状态；不填写时不过滤。",
    "state_uuid": "物料状态记录的唯一编号（UUID）。",
    "status": "状态筛选值；不填写时不过滤。",
    "subject_id": "要查询或删除摆放信息的对象编号。",
    "substance_uuid": "当前成分记录的唯一编号（UUID）。",
    "target_node_uuid": "只运行到或从指定节点开始；不填写时使用工作流默认入口。",
    "task_uuid": "工作流任务的唯一编号（UUID）。",
    "telemetry_type": "设备状态类型；不填写时接收全部类型。",
    "template_id": "库存模板编号。",
    "template_uuid": "资源模板或节点模板的唯一编号（UUID）。",
    "type": "类型筛选值；不填写时不过滤。",
    "window_s": "时间线向前查询的秒数。",
    "with_spec": "是否在返回结果中包含提交时的完整工作流定义。",
    "workflow_id": "一次工作流运行或工作流定义的编号。",
    "workflow_node_template_uuid": "工作流节点模板的唯一编号（UUID）；不填写时不过滤。",
    "workflow_type": "工作流类型；不填写时不过滤。",
    "workflow_uuid": "工作流或实验操作的唯一编号（UUID）。",
    "zone_id": "实验室区域编号。",
}


REQUEST_BODY_MEANINGS = {
    "ApplyRequest": "要应用的工作流源码候选信息。",
    "DebugWorkflowTaskCommandRequest": "调试任务控制命令。",
    "DebugWorkflowTaskCreateRequest": "调试工作流任务的创建信息。",
    "DeviceActionRunCreateRequest": "设备动作任务的创建信息。",
    "DeviceStateReportIn": "设备及其最新属性值。",
    "DraftWriteRequest": "要保存的 Python 源码草稿和调用方当前看到的修改版本。",
    "ErrorDecisionIn": "设备错误的处理方式和原因。",
    "FailedMaterialTransferSettlementRequest": "转运失败后确认的物料实际变化。",
    "GraphWriteRequest": "工作流当前修改版本号、全部节点和全部连线。",
    "IngressReservationCreateRequest": "入库预留信息。",
    "InsertCompositeWorkflowRequest": "要插入的子工作流及其设备、位置和参数。",
    "InventoryCommand": "要执行的库存操作命令。",
    "JobAddReq": "要下发的设备、动作和动作参数。",
    "JobFinishIn": "设备任务是否成功及其返回内容。",
    "LegacyMaterialQueryRequest": "物料编号列表或资源编号查询条件。",
    "LegacyWorkflowImportRequest": "旧格式工作流的名称、节点、连线和其他信息。",
    "ManualConfirmationDecisionRequest": "人工确认的处理结果、处理人和备注。",
    "MaterialCreateRequest": "新物料的模板、名称、条码、父级和初始位置。",
    "MaterialStateRequest": "新增的物料状态内容。",
    "MaterialUpdateRequest": "要修改的物料字段和位置。",
    "OperationCategoryCreateRequest": "新实验操作类别的名称和排序值。",
    "OperationCategoryUpdateRequest": "要修改的实验操作类别字段。",
    "PublishWorkflowContractRequest": "要发布的工作流修改版本号。",
    "ReagentBatchRequest": "要批量登记的容器级试剂列表和提交方式。",
    "ReagentCreateRequest": "新试剂库存的信息。",
    "ReagentInfoBatchRequest": "要批量登记的试剂身份列表和提交方式。",
    "ReagentInfoCreateRequest": "新试剂信息。",
    "ReagentInfoUpdateRequest": "要修改的试剂信息字段。",
    "ReagentUpdateRequest": "要修改的试剂库存字段。",
    "ResourceTemplateSyncRequest": "要同步的资源模板列表。",
    "ResourceTemplateUpdateRequest": "要修改的资源模板字段。",
    "SampleCreateRequest": "新样品的信息。",
    "SampleUpdateRequest": "要修改的样品字段。",
    "StationWorkflowInvocationRequest": "工站要创建的工作流任务信息。",
    "SubstanceCreateRequest": "物料中的新成分信息。",
    "SubstanceUpdateRequest": "要修改的物料成分字段。",
    "UncertainJobResolutionRequest": "状态不确定的节点任务最终结果和原因。",
    "WorkflowBatchDeleteRequest": "要删除的节点唯一编号和连线唯一编号。",
    "WorkflowCreateRequest": "新工作流或实验操作的名称、类型和说明。",
    "WorkflowDuplicateRequest": "复制后使用的新名称；不填写时由服务生成。",
    "WorkflowEdgeCreateRequest": "连线两端的节点和连接点。",
    "WorkflowInterventionDecisionRequest": "待处理事项的修改版本号、选择项和处理结果。",
    "WorkflowNodeCreateRequest": "新节点的模板、名称、位置、参数和执行设置。",
    "WorkflowNodePatchRequest": "要修改的节点字段。只会修改明确提供的字段。",
    "WorkflowRunPreflightRequest": "运行检查使用的入口、输入和库存选择。",
    "WorkflowTaskCommandRequest": "工作流任务控制命令。",
    "WorkflowTaskCreateRequest": "工作流任务的工作流、运行方式、输入和库存选择。",
    "WorkflowUpdateRequest": "工作流或实验操作修改后的根信息。",
}
